### ISSUE TITLE
Install Fails on M1 Mac

### ISSUE THREAD

**Issue by seandenigris** [scrapinghub/python-crfsuite#149]
I tried to do `pipenv install python-crfsuite`, but got 12 errors.

Platform details:
- Python 3.10.2
- ARM Mac (M1 Max)
- macOS 12.4
- Xcode 13.4.1

Here is the output: [crf_errors.txt](https://github.com/scrapinghub/python-crfsuite/files/8970337/crf_errors.txt)

I'm guessing maybe it's a Mac ARM-specific problem, since AFAICT from other issues, the python3 problems have been solved.

**Comment by nmalaguti** [comment]
I've seen a similar problem when only having the CommandLineTools installed.

Install worked correctly for me when using the include path

```
-I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include
```

instead of 

```
 -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include
```

I'm not sure how to force `-I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include` to appear first in the list of include paths.

**Comment by krkd** [comment]
Issue is not connected to python-crfsuite but with local configuration. Check  [comment](https://github.com/RcppCore/Rcpp/issues/1160#issuecomment-835119201) it may solve your problem

**Comment by whwright** [comment]
I am having the same errors even after reading the thread about xcode select path, and my error output has `/Library/Developer/CommandLineTools/*`. Any updates on this?

**Comment by fgregg** [comment]
should work now

**Comment by bebaek** [comment]
I had the same problem with python 3.9 but could install it fine with python 3.10.
