### ISSUE TITLE
how to add bigram features

### ISSUE THREAD

**Issue by yyaodong** [scrapinghub/python-crfsuite#41]
Hi,

I was following the simple example about a name entity task. However it doesn't contain how to add bigram features, nor can I find any documents. Will you please guide me how to add the bigram features? Thanks.

**Comment by kmike** [comment]
Hey @yyaodong,

What do you mean by a 'bigram feature'? It can means several different things.

**Comment by yyaodong** [comment]
Thanks for the quick response.

The bigram I want to add is for example, the link between the predicting label of the current word and the label of previous word.

Thx!

**Comment by kmike** [comment]
Unfortunately this is not possible in CRFSuite because it implements only first order transition probabilities, so you can't have dependencies between *labels* for more than 1 step behind. 

You can somewhat approximate it by adding a feature which takes *input* of several nearby steps in account - e.g. you can take previous word and current word, join them using a separator and use as a feature value.

**Comment by yyaodong** [comment]
In CRF++, the bigram feature can be easily incorporated by using "B" in the feature template. In CRFSuite's case, does that mean to realise a linear chain CRF is impossible?

Thanks

**Comment by yyaodong** [comment]
Be more precise, in my understanding, a linear-chain CRF means you can build your features on (xt, yt, yt-1), I want to incorporate the feature based on the yt and yt-1, e.g., in pos tagging, a noun is usually followed by an adjective, then the feature of Adjective-Noun is worth putting in. Is there a way in CRFsuite to take into account this situation?

**Comment by kmike** [comment]
Aha, I see. In CRFsuite you always have a (yt, yt-1) feature - it is there by default, but you can't condition it on input like in CRF++. So you have two types of features in CRFsuite:

* for each possible (a, b) label pair there is `I(yt=a, yt-1=b)`, feature i.e. it is 1 if `yt=a` and  `yt-1=b`, and 0 otherwise - it is called 'transition feature', and it is enabled by default.
* input features have form `f(x)I(yt=a)`, where f(x) is a user-supplied function which looks at the input sequence. This is what you define.

In CRF++ or Wapiti a third kind of features is possible: `f(x)I(yt=a, yt-1=b)`; they are not implemented in CRFsuite.

**Comment by yyaodong** [comment]
Perfect! That's crystal clear to me now. Thanks for your time!

**Comment by tisdall** [comment]
I know this is an old issue, but looking for some clarifications related to this...

Since CRFsuite automatically includes `I(yt=a, yt-1=b)` isn't that the same as the CRF++ template having a single `B` line?  I think that's what's said here, but I'm not entire sure.

**Comment by kmike** [comment]
@tisdall yes, it is the same as a single `B` line in CRF++ template.

**Comment by deepakiim** [comment]
Again I know this is an old issue, but looking for some clarifications.

1. How to use ```xt, xt-1``` or even ```xt, xt-1, xt-2...xt-n``` as a feature in python-crfsuite?
2. How to use a float feature instead of buckets in python-crfsuite? Any example for this implementation?
