### ISSUE TITLE
Can I train a crf model using multiple thread ?

### ISSUE THREAD

**Issue by luosmart** [scrapinghub/python-crfsuite#83]
Thank you very much.

**Comment by oasis789** [comment]
Is these even possible with the current setup?

**Comment by kmike** [comment]
No, it is not possible now; this is a limitation of CRFSuite C++ library. You can only train several separate models in parallel for hyperparameter search. There are some attempts to make CRFSuite muti-threaded (https://github.com/chokkan/crfsuite/pulls), but nothing is merged. 

I'm closing this ticket because it is better to be discussed in crfsuite bug tracker.
